import { StyleSheet } from 'react-native';

export const getProfileStyles = (colors, isDark) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    centerContainer: {
      flex: 1,
      backgroundColor: colors.background,
      justifyContent: 'center',
      alignItems: 'center',
    },
    loadingText: {
      marginTop: 12,
      color: colors.textSecondary,
      fontSize: 14,
    },
    emptyText: {
      fontSize: 16,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    topBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.card,
    },
    backIconBtn: {
      padding: 6,
    },
    backArrow: {
      fontSize: 22,
      fontWeight: '700',
      color: colors.text,
    },
    topBarTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
    },
    profileWrapper: {
      flex: 1,
      justifyContent: 'center',
      padding: 20,
    },
    profileCard: {
      backgroundColor: colors.card,
      borderRadius: 24,
      padding: 24,
      margin: 16,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDark ? 0.35 : 0.06,
      shadowRadius: 10,
      elevation: 3,
    },
    avatarWrap: {
      position: 'relative',
      marginBottom: 14,
    },
    avatar: {
      width: 96,
      height: 96,
      borderRadius: 48,
      borderWidth: 3,
      borderColor: colors.primary,
    },
    avatarEditIconBadge: {
      position: 'absolute',
      bottom: 2,
      right: 2,
      backgroundColor: colors.primary,
      borderRadius: 14,
      width: 28,
      height: 28,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: colors.card,
    },
    name: {
      fontSize: 20,
      fontWeight: '800',
      color: colors.text,
    },
    username: {
      fontSize: 14,
      color: colors.primary,
      fontWeight: '600',
      marginTop: 2,
    },
    email: {
      fontSize: 13,
      color: colors.textSecondary,
      marginTop: 4,
    },
    bio: {
      fontSize: 13,
      color: colors.text,
      textAlign: 'center',
      marginTop: 12,
      paddingHorizontal: 16,
      lineHeight: 18,
    },
    noBio: {
      fontSize: 12,
      color: colors.textSecondary,
      fontStyle: 'italic',
      marginTop: 10,
    },
    editBtn: {
      borderWidth: 1,
      borderColor: colors.primary,
      backgroundColor: isDark ? 'rgba(59, 130, 246, 0.12)' : 'rgba(59, 130, 246, 0.08)',
      borderRadius: 12,
      paddingHorizontal: 18,
      paddingVertical: 9,
      marginTop: 14,
    },
    editBtnText: {
      color: colors.primary,
      fontWeight: '700',
      fontSize: 13,
    },
    followToggleBtn: {
      borderRadius: 12,
      paddingHorizontal: 28,
      paddingVertical: 10,
      marginTop: 16,
      minWidth: 140,
      alignItems: 'center',
    },
    followBtn: {
      backgroundColor: colors.primary,
    },
    followingBtn: {
      backgroundColor: isDark ? 'rgba(59, 130, 246, 0.15)' : '#EFF6FF',
      borderWidth: 1.5,
      borderColor: colors.primary,
    },
    followToggleBtnText: {
      fontWeight: '700',
      fontSize: 14,
    },
    followBtnText: {
      color: '#fff',
    },
    followingBtnText: {
      color: colors.primary,
    },
    statsRow: {
      flexDirection: 'row',
      width: '100%',
      justifyContent: 'space-around',
      marginVertical: 20,
      paddingTop: 16,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    statBox: {
      alignItems: 'center',
    },
    statNumber: {
      fontSize: 16,
      fontWeight: '800',
      color: colors.primary,
    },
    statLabel: {
      fontSize: 12,
      color: colors.textSecondary,
      marginTop: 2,
    },
    postsSectionHeader: {
      width: '100%',
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      alignItems: 'flex-start',
    },
    postsSectionTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
    },
    emptyPostsText: {
      textAlign: 'center',
      color: colors.textSecondary,
      fontSize: 13,
      marginVertical: 20,
    },
    logoutBtn: {
      backgroundColor: isDark ? 'rgba(239, 68, 68, 0.15)' : '#FEE2E2',
      borderRadius: 14,
      width: '100%',
      paddingVertical: 12,
      alignItems: 'center',
      borderWidth: isDark ? 1 : 0,
      borderColor: isDark ? 'rgba(239, 68, 68, 0.3)' : 'transparent',
    },
    logoutBtnText: {
      color: colors.heart,
      fontWeight: '700',
      fontSize: 15,
    },
    guestPlanetIcon: {
      fontSize: 48,
      marginBottom: 12,
    },
    guestContainer: {
      backgroundColor: colors.card,
      borderRadius: 24,
      padding: 24,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
      margin: 20,
      marginTop: 60,
    },
    guestTitle: {
      fontSize: 20,
      fontWeight: '800',
      color: colors.text,
      marginBottom: 8,
    },
    guestSubtitle: {
      fontSize: 14,
      color: colors.textSecondary,
      textAlign: 'center',
      marginBottom: 24,
      lineHeight: 20,
    },
    primaryBtn: {
      backgroundColor: colors.primary,
      borderRadius: 14,
      width: '100%',
      paddingVertical: 14,
      alignItems: 'center',
      marginBottom: 10,
    },
    primaryBtnText: {
      color: '#fff',
      fontWeight: '700',
      fontSize: 15,
    },
    secondaryBtn: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      width: '100%',
      paddingVertical: 14,
      alignItems: 'center',
      backgroundColor: isDark ? colors.inputBg : 'transparent',
    },
    secondaryBtnText: {
      color: colors.text,
      fontWeight: '600',
      fontSize: 15,
    },
    backBtnPill: {
      marginTop: 16,
      backgroundColor: colors.primary,
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 10,
    },
    backBtnText: {
      color: '#fff',
      fontWeight: '700',
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.65)',
      justifyContent: 'center',
      padding: 20,
    },
    modalContent: {
      backgroundColor: colors.card,
      borderRadius: 20,
      padding: 22,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.35,
      shadowRadius: 20,
      elevation: 10,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: '800',
      color: colors.text,
      marginBottom: 16,
    },
    modalAvatarSection: {
      alignItems: 'center',
      marginBottom: 16,
    },
    modalAvatarTouch: {
      position: 'relative',
      marginBottom: 8,
    },
    modalAvatarPreview: {
      width: 88,
      height: 88,
      borderRadius: 44,
      borderWidth: 3,
      borderColor: colors.primary,
    },
    cameraIconPill: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      backgroundColor: colors.primary,
      borderRadius: 14,
      width: 28,
      height: 28,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: colors.card,
    },
    cameraIconText: {
      fontSize: 13,
    },
    changePhotoBtnText: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.primary,
      marginTop: 4,
    },
    removeSelectedPhotoText: {
      fontSize: 12,
      color: colors.heart,
      marginTop: 4,
      fontWeight: '600',
    },
    inputLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSecondary,
      marginBottom: 6,
    },
    textInput: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      padding: 12,
      fontSize: 14,
      color: colors.text,
      backgroundColor: colors.inputBg,
      marginBottom: 14,
    },
    bioInput: {
      height: 90,
      textAlignVertical: 'top',
    },
    modalActionRow: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 12,
      marginTop: 8,
    },
    modalCancelBtn: {
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 10,
    },
    modalCancelText: {
      color: colors.textSecondary,
      fontWeight: '600',
    },
    modalSaveBtn: {
      backgroundColor: colors.primary,
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 10,
    },
    modalSaveText: {
      color: '#fff',
      fontWeight: '700',
    },
  });

export default getProfileStyles;
